services:
  - type: web
    name: sentimentai-backend
    runtime: python
    rootDir: backend
    buildCommand: apt-get install -y tesseract-ocr && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FLASK_DEBUG
        value: false
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract

  - type: web
    name: sentimentai-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
